"""empty message

Revision ID: 16a666472953
Revises: 39602e75a90b
Create Date: 2024-02-27 23:36:06.633036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a666472953'
down_revision = '39602e75a90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention')
    op.drop_table('therapist_intervention')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_intervention',
    sa.Column('therapist_id', sa.INTEGER(), nullable=False),
    sa.Column('intervention_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('therapist_id', 'intervention_id')
    )
    op.create_table('intervention',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
