"""empty message

Revision ID: 349e4032b86d
Revises: 682fa9897234
Create Date: 2024-02-28 08:53:03.260313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349e4032b86d'
down_revision = '682fa9897234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_format',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('session_format_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['session_format_id'], ['session_format_model.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'session_format_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_format')
    # ### end Alembic commands ###
