"""empty message

Revision ID: 682fa9897234
Revises: b4bc87bacbda
Create Date: 2024-02-28 06:00:53.380742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682fa9897234'
down_revision = 'b4bc87bacbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_format_model', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('therapist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliation', sa.Text(), nullable=True))
        batch_op.drop_column('affilitation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affilitation', sa.TEXT(), nullable=True))
        batch_op.drop_column('affiliation')

    with op.batch_alter_table('session_format_model', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
